### PR TITLE
fix retry error when multipart request

### PR DESCRIPTION
**Pull request by wolru**

### CODE REVIEW

**Comment by rodion-m** [comment]
Hi @wolru ! Thank you for conributing.
Could you please add some tests for this?

**Comment by rodion-m** [comment]
@aweiand could you please reproduce your issue (#15) after applying updated from this PR?

**Comment by aweiand** [comment]
@rodion-m responded in the thread #15 ;-)

**Comment by rodion-m** [comment]
> @rodion-m responded in the thread #15 ;-)

Ok, thank you for checking it. I'll merge it and then try to make a fix.

**Pull request merged**
