### PR TITLE
revert: diox change

### PR DESCRIPTION
**Pull request by SebastianKlaiber**
Now that diox is dio, this PR will revert the changes to diox.

### CODE REVIEW

**Review by iTEEECH — APPROVED** [review]
@

**Comment by SebastianKlaiber** [comment]
@rodion-m if you have time, could you also review this PR? Thank you.

**Comment by rodion-m** [comment]
@SebastianKlaiber  Sure. I have a question about backward compatibility. Will this new version of dio_smart_retry work with dio 4.x?

**Comment by iTEEECH** [comment]
@rodion-m  No unfortunately because the DioX changes have been merged directly into Dio 5.0.0 including the change of DioError.response to badResponse or the implicit contentType has been removed.

**Comment by rodion-m** [comment]
> @rodion-m No unfortunately because the DioX changes have been merged directly into Dio 5.0.0 including the change of DioError.response to badResponse or the implicit contentType has been removed.
> 
> So, maybe write it in the README.md ?

Yes, we definitely should mention it. Also, perhaps it costs to release the new dio_smart_retry as a prerelease while dio 5.0 is not so populated?

**Comment by SebastianKlaiber** [comment]
I also think a prerelease would be the best decision.

**Comment by Zazo032** [comment]
Dio 5 is out so I don't really think a prerelease version would make sense now, if the version this plugin depends on is already released

**Comment by Shakle** [comment]
in Dio 5 I get this:

The element type 'RetryInterceptor' can't be assigned to the list type 'Interceptor'.

**Comment by rodion-m** [comment]
Merged. Thank you for contributing. The new version with dio 5.0.0 support is available as `dio_smart_retry: ^5.0.0`.

**Pull request merged**
