### PR TITLE
Fix file not found error

### PR DESCRIPTION
**Pull request by DmitryGaimaldinov**
Currently `MultipartFileRecreatable` reuses same stream across all retry requests. This cause `FileSystemException: File closed` bacause stream can be listened only once. This behavior described in this issue: https://github.com/cfug/dio/issues/482#issuecomment-534875858. Accordingly, this error throws in current test too: multipart_retry_tests.dart -> test 'Retry for MultipartFileRecreatable is retrying'.

The best solution is to get rid of `MultipartFileRecreatable` and use `MultipartFile.clone()` which internally recreates stream and fixes current `File closed` error. `FormData.clone()` internally uses `MultipartFile.clone()` to recreate all MultipartFile's.

One more advance of this approach is that the [retrofit](https://pub.dev/packages/retrofit) package will get support to retry MultipartFile's as it currently cannot generate code for `MultipartFileRecreatable`

### CODE REVIEW

**Comment by DmitryGaimaldinov** [comment]
@rodion-m

**Comment by rodion-m** [comment]
@DmitryGaimaldinov Nice! Thanks a lot for the contribution. I'll up the major version, since it's a breaking change.

**Comment by DmitryGaimaldinov** [comment]
@rodion-m, thanks for paying attention and merging. Can you publish a new version on pub.dev, please?

**Comment by oantacamelia** [comment]
We are also looking forward to this release

**Pull request merged**
